django_test2/mysite/guestbook/urls.py
from django.urls import path
from .views import GuestbookListView, GuestbookCreateView

app_name = 'guestbook'

urlpatterns = [
    path('', GuestbookListView.as_view(), name='guestbook'),
    path('add/', GuestbookCreateView.as_view(), name='add_guestbook_post'),
]

django_test2/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('guestbook/', include('guestbook.urls')),
]

django_test2/mysite/guestbook/models.py
from django.db import models

class Post(models.Model):
    author = models.CharField(max_length=100)
    message = models.TextField(max_length=1000)
    creation_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.author
        

django_test2/mysite/guestbook/views.py
from django.views.generic import ListView, CreateView
from django.urls import reverse_lazy
from .models import Post

class GuestbookListView(ListView):
    model = Post
    template_name = 'guestbook/guestbook.html'
    context_object_name = 'latest_posts'
    ordering = ['-creation_date']
    paginate_by = 10

class GuestbookCreateView(CreateView):
    model = Post
    template_name = 'guestbook/guestbook_form.html'
    fields = ['author', 'message']
    success_url = reverse_lazy('guestbook:guestbook')

django_test2/mysite/guestbook/templates/guestbook/guestbook.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Guestbook</title>
  <style>
    /* Add your styles here */
    body {
      background-color: #1c1c1c;
      color: #fff;
      font-family: Roboto, sans-serif;
    }
  </style>
</head>
<body>
  <header>
    <h1>Guestbook</h1>
  </header>
  <main>
    <!-- Form to add new guestbook posts -->
    <form method="POST" action="{% url 'guestbook:add_guestbook_post' %}">
      {% csrf_token %}
      <label for="author">Author:</label>
      <input type="text" id="author" name="author" required>
      <br>
      <label for="message">Message:</label>
      <textarea id="message" name="message" required></textarea>
      <br>
      <button type="submit">Add Post</button>
    </form>
    <!-- List of latest guestbook messages -->
    <h2>Latest Messages</h2>
    <ul>
      {% for post in latest_posts %}
        <li>
          <strong>{{ post.author }}</strong> - {{ post.creation_date|date:"F d, Y H:i" }}<br>
          {{ post.message|linebreaks }}
        </li>
      {% empty %}
        <li>No messages yet.</li>
      {% endfor %}
    </ul>
  </main>
</body>
</html>